# Generated by Django 5.1.2 on 2025-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nota1', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nota3', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nota4', models.DecimalField(decimal_places=1, max_digits=5)),
                ('media', models.DecimalField(decimal_places=1, editable=False, max_digits=5)),
                ('situacao', models.CharField(editable=False, max_length=10)),
            ],
        ),
    ]
